events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	sendfile on;

	keepalive_timeout 65;

	server {
		listen 80;
		server_name _;
		server_tokens off;

		location /.well-known/acme-challenge/ {
			root /var/www/certbot;
		}

		location / {
			return 301 https:///;
		}
	}

	server {
		listen 4443 ssl proxy_protocol;
		server_name stream.breezeshot.com;
		server_tokens off;

		ssl_certificate /etc/letsencrypt/live/stream.breezeshot.com/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/stream.breezeshot.com/privkey.pem;
		include /etc/letsencrypt/options-ssl-nginx.conf;
		ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

		set_real_ip_from				proxy;
		real_ip_header					proxy_protocol;

		location / {
			proxy_pass					http://edumeet-client:80/;
		}

		location /socket.io/ {
			proxy_pass					http://edumeet-room-server:8443/socket.io/;
			proxy_http_version			1.1;

			proxy_set_header			X-Forwarded-For ;
			proxy_set_header			Upgrade ;
			proxy_set_header			Connection "upgrade";
		}

		location /internal/rooms/participants {
			proxy_pass				http://edumeet-room-server:8443/internal/rooms/participants;
			proxy_http_version		1.1;
			proxy_set_header		Host ;
			proxy_set_header		X-Real-IP ;
			proxy_set_header		X-Forwarded-For ;
			proxy_set_header		X-Forwarded-Proto ;
		}
		location /kc/
		{
			proxy_set_header Host ;
			proxy_set_header X-Real-IP ;
			proxy_set_header X-Forwarded-For ;
			proxy_set_header X-Forwarded-Host ;
			proxy_set_header X-Forwarded-Server ;
			proxy_set_header X-Forwarded-Port 443;
			proxy_set_header X-Forwarded-Proto https;

			proxy_pass http://keycloak:8080/kc/;
		}
		#location /pgadmin/
		#{
		#		proxy_set_header X-Script-Name /pgadmin;
		#		proxy_set_header Host ;
		#		proxy_pass http://pgadmin:80/;
		#		proxy_redirect off;
		#}
		location /mgmt/
		{
			proxy_pass http://edumeet-management-server:3030/;
			proxy_ssl_verify off;
			proxy_set_header X-Forwarded-For ;
			proxy_set_header Host ;

			proxy_http_version 1.1;
			proxy_set_header Upgrade ;
			proxy_set_header Connection "upgrade";

			proxy_buffer_size 128M;
			proxy_buffers 4 256M;
			proxy_busy_buffers_size 256M;
			proxy_set_header Host ;
			proxy_redirect off;

		}
		location /auth/callback
		{
			proxy_buffer_size 128M;
			proxy_buffers 4 256M;
			proxy_busy_buffers_size 256M;
			proxy_set_header Host ;
			proxy_redirect off;
			proxy_pass http://edumeet-management-server:3030/auth/callback;

		}

	}
}

stream {
	map   {
		stream.breezeshot.com http_backend;
		stream.breezeshot.com turn_server;
	}

	upstream http_backend {
		server proxy:4443;
	}

	upstream turn_server {
		server proxy:3479;
	}

	server {
		listen 443;
		ssl_preread on;
		proxy_pass ;
		proxy_buffer_size 10m;
		proxy_protocol on;
	}

	server {
		listen 3479 ssl proxy_protocol;

		ssl_certificate /etc/letsencrypt/live/stream.breezeshot.com/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/stream.breezeshot.com/privkey.pem;
		ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

		proxy_ssl	off;
		proxy_pass	0.0.0.0:3478;
	}
}
